[project]
name = "sdr-tool"
version = "0.1.0"
description = "sdr-tool(s) collection"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[dependency-groups]
dev = [
    "ruff>=0.11.2",
]
